### ISSUE TITLE
Crtl D clashes with Chome key mappings

### ISSUE THREAD

**Issue by neurobe** [rclai/meteor-ddp-inspector#2]
having trouble finding out how to turn off the default key mappings, so can't use...

**Comment by rclai** [comment]
What about shift + D? Would that work better?

**Comment by neurobe** [comment]
Hi Richard,
I switch between Windows and Linux. Currently under Windows OS and there 
Chrome doesn't do anything with shft D, but for contrl D it wants to add 
a bookmark.

So I guess shft D will be ok.

thanks for donating this work

bruce

**Comment by rclai** [comment]
Added shift + d. Sorry took so long :(.
